name: chawi_hotel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  shimmer: ^3.0.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/


