# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!
use_modular_headers!

# CocoaPods analytics send network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_application_path = File.expand_path('../..', __FILE__)
eval(File.read(File.join(flutter_application_path, 'ios', 'flutter', 'podhelper.rb')), binding)
