name: Build iOS App (Simulator)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Clean Flutter
        run: flutter clean

      # Build for simulator (auto-generates pods)
      - name: Build iOS App for Simulator
        run: flutter build ios --simulator --no-codesign

      # Upload the .app as artifact
      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphonesimulator/Runner.app
