name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 3. Get dependencies
      - run: flutter pub get

      # 4. Build the iOS app for simulator
      - run: flutter build ios --simulator --no-codesign

      # 5. Upload the .app as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphonesimulator/Runner.app
